removed debug

diff --git a/zabbix/zabbix-2.0.14/debian/zabbix-agent.postinst b/zabbix/zabbix-2.0.14/debian/zabbix-agent.postinst
--- a/zabbix/zabbix-2.0.14/debian/zabbix-agent.postinst
+++ b/zabbix/zabbix-2.0.14/debian/zabbix-agent.postinst
@@ -21,7 +21,6 @@ if [ "$1" = "configure" ]; then
 
     cp $CONFFILE1 $CONFFILE_DEST1.new
     if [ "$ZBX_MODE" = "active" ]; then
-      echo "Salut les loosers" >&2
       sed -e 's/^ServerActive=.*/ServerActive=zabbix-20-1.quanta-computing.com/g' < $CONFFILE1 > $CONFFILE_DEST1.new
     fi
     ucf --debconf-ok $CONFFILE_DEST1.new $CONFFILE_DEST1
@@ -47,7 +46,7 @@ if [ "$1" = "configure" ]; then
     case $RET in
       *Apache*)
         ROLE=front
-        PKGS="$PGKS zabbix-quanta-apache"
+        PKGS="$PKGS zabbix-quanta-apache"
       ;;
     esac
     case $RET in
@@ -57,6 +56,7 @@ if [ "$1" = "configure" ]; then
         else
           ROLE=database
         fi
+        PKGS="$PKGS zabbix-quanta-mysql"
       ;;
     esac
     if [ -z "$ROLE" ]; then
@@ -91,10 +91,8 @@ if [ "$1" = "configure" ]; then
       then
         echo "Registered $NAME on Quanta, please check if everything is OK in Quanta (settings -> system)" >&2
       else
-        echo "Uh oh... An error occured while registering zabbix-agent" >&2
+        echo "Uh oh... An error occured while auto-registering zabbix-agent to Quanta, please configure it manually" >&2
       fi
-    else
-      echo "Auto-registration is not possible (token not provided)" >&2
     fi
 fi
 
